name: Deploy Vikunja to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: europe-west1
      SERVICE: vikunja
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_GH_SVC_ACCOUNT_JSON_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/sebsandbbox/vikunja/vikunja:latest .
          docker push europe-west1-docker.pkg.dev/sebsandbbox/vikunja/vikunja:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: europe-west1-docker.pkg.dev/sebsandbbox/vikunja/vikunja:latest
          region: ${{ env.REGION }}
          env_vars: |
            VIKUNJA_PORT=8080
            VIKUNJA_DATABASE_TYPE=postgres
            VIKUNJA_DATABASE_HOST=${{ secrets.PG_VIKUNJA_IP }}
            VIKUNJA_DATABASE_USER=${{ secrets.PG_VIKUNJA_USER }}
            VIKUNJA_DATABASE_PASSWORD=${{ secrets.PG_VIKUNJA_PASSWORD }}
            VIKUNJA_DATABASE_DATABASE=${{ secrets.PG_VIKUNJA_DATABASE }}
