name: Deploy Vikunja to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: europe-west9
      SERVICE: vikunja
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_GH_SVC_ACCOUNT_JSON_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev
      - name: Build and push Docker image
        run: |
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PG_VIKUNJA_USER }}/vikunja:latest .
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PG_VIKUNJA_USER }}/vikunja:latest

      - name: Ensure Cloud Run service exists
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image europe-west9-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/vikunja:latest \
            --region ${{ env.REGION }} \
            --no-traffic \
            --platform managed \
            --quiet || true

      - name: Remove old VIKUNJA_DATABASE_PASSWORD env var if exists
        run: |
          gcloud run services update ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --remove-env-vars VIKUNJA_DATABASE_PASSWORD \
            --platform managed \
            --quiet || true

      - name: Wait for env var removal to propagate
        run: sleep 10

      - name: Mask DB password in logs
        run: echo "::add-mask::${{ secrets.PG_VIKUNJA_PASSWORD }}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PG_VIKUNJA_USER }}/vikunja:latest
          region: ${{ env.REGION }}
          env_vars: |
            VIKUNJA_SERVICE_PORT=3456
            VIKUNJA_DATABASE_TYPE=postgres
            VIKUNJA_DATABASE_HOST=${{ secrets.PG_VIKUNJA_IP }}
            VIKUNJA_DATABASE_USER=${{ secrets.PG_VIKUNJA_USER }}
            VIKUNJA_DATABASE_DATABASE=${{ secrets.PG_VIKUNJA_DATABASE }}
          secrets: |
            VIKUNJA_DATABASE_PASSWORD=vikunja-db-password:latest
